version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: company_search_db
    restart: always

    environment:
      POSTGRES_DB: company_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
